class AppRoutes {
  static const HOME = '/';
  static const USER_FORM = '/user-form';
  static const USER_RESIDENCIA = '/user-residencia';
  static const USER_REGISTRO = '/user-registro';
  static const USER_CASA  = '/user-casa';
  static const USER_LOCALIZADA  = '/user-localizada';
  static const USER_OCUPACAO  = '/user-ocupacao';
  static const USER_ESCOLARIDADE  = '/user-escolaridade';
  static const USER_DIAGNOSTICO  = '/user-diagnostico';
  static const USER_ORIENTACOES  = '/user-orientacoes';
  static const USER_AGENTES  = '/user-agentes';
  static const USER_EVITAR  = '/user-evitar';
  static const USER_CURA  = '/user-cura';
  static const USER_VEZES  = '/user-vezes';
  static const USER_TIPO  = '/user-tipo';
  static const USER_TEMPO  = '/user-tempo';
  static const USER_COMPRIMIDOS = '/user-comprimidos';
  static const USER_MOTIVO= '/user-motivo';
  static const USER_SOBRARAM= '/user-sobraram';
  static const USER_SEGUIR= '/user-seguir';
  static const USER_NAOSEGUIR= '/user-naoseguir';
  static const USER_REMEDIO= '/user-remedio';
  static const USER_BEM= '/user-bem';
  static const USER_MAL= '/user-mal';
  static const URL_SIGN_UP = 'https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=AIzaSyB74Dx5JmGqM2s5zZFKZxUH5vOGGljL3fE';
  static const LOGIN = 'https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyB74Dx5JmGqM2s5zZFKZxUH5vOGGljL3fE';
  static const USER_PESSOAS = '/user-pessoas';
  static const USER_RENDA = '/user-renda';
  static const USER_HOME = '/user-home';
  static const USER_TRAT = '/user-tratamento';
  static const TRAT_VIVAX_OVALE = '/trat_vivax_ovale';
  static const TRAT_VIVAX_OVALE_GESTANTE = '/trat_vivax_ovale_gestante';
  static const TRAT_MALARAE = '/trat_malarae';
  static const TRAT_FALCIPARUM = '/trat_falciparum';
  static const TRAT_FALCIPARUM_GESTANTE = '/trat_falciparum_gestante';
  static const TRAT_MISTA = '/trat_mista';
  static const DOCUMENTS = '/documents_screen';
  static const CLOCK = '/clock';
  static const TRAT_RECORRENCIA60_VIVAX = '/trat_recorrencia60_vivax';
  static const TRAT_VIVAX_DEFICIENCIA_G6PD = '/trat_vivax_deficiencia_g6pd';
}